// SPDX-License-Identifier: MIT
// Copyright (c) 2026 rt-devon2 test org
import { IsOptional, IsString } from 'class-validator';

/** Mechanical DTO scaffold #48 (generated by scripts/scaffold-dtos.ts). */
export class Dto048 {
    @IsString()
    public id: string;

    @IsOptional()
    @IsString()
    public label?: string;
}
